[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "^1.19.1"

[[override]]
  name = "k8s.io/apimachinery"
  revision = "75b8dd260ef0469d96d578705a87cffd0e09dab8"

[[override]]
  name = "k8s.io/client-go"
  version = "v3.0.0-beta.0"

[[override]]
  name = "github.com/caicloud/loadbalancer-controller"
  branch = "master"
